### ISSUE TITLE
Crop image not working

### ISSUE THREAD

**Issue by datnq201088** [sotospez/sotos.crop-image#10]
I try to example, but it's not working when i click crop image
http://plnkr.co/edit/mrlF7s?p=preview

Why image not get? 
Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at Error (native)
    at getImage (http://run.plnkr.co/f4OJayJFDEyb6rcu/sotos.crop-image.min.js:11:8562)

Help me please!

**Comment by sotospez** [comment]
hi i think is problem with plnkr DataUrl or ( Access-Control-Allow-Origin)
http://stackoverflow.com/questions/22710627/tainted-canvases-may-not-be-exported
try http://sotos.gr/demos/crop-image/
thanks

**Comment by datnq201088** [comment]
thank you ;)
