### ISSUE TITLE
How to limit crop selection in side image?

### ISSUE THREAD

**Issue by datnq201088** [sotospez/sotos.crop-image#11]
I have bug when i move crop selection. The crop selection is not limited in side image. After I cropped , apart of cropped image is  dark.
![crop-image-error](https://cloud.githubusercontent.com/assets/7147240/6866096/2e8267f8-d4a7-11e4-9c19-fd56e3451008.png)

**Comment by sotospez** [comment]
yes is no limit try to use $scope.options.outputImageType= "png";

**Comment by NeevShah** [comment]
Hi @sotospez, I have similar issue.  But my case I want to limit crop tool to not go outside the canvas? Can you please show me the way to restrict crop tool inside the boundaries?

**Comment by zaidchauhan** [comment]
Hello sotospez,

I have made some changes to solve this issue. I forked this repository and changed 'https://github.com/zaidchauhan/sotos.crop-image/blob/master/dist/sotos.crop-image.js' file there. I would like to make pull request to push this changes in to your project

**Comment by sotospez** [comment]
thanks  zaidchauhan 
i merged and upload the full project with src 
sorry for the delay here in greece we have some problems with internet...
