### ISSUE TITLE
Possibility to lock rotation into predefined steps

### ISSUE THREAD

**Issue by kirbo** [sotospez/sotos.crop-image#16]
Hi,
could you add a possibility to lock rotation into some predefined steps, something like:

    $scope.options.rotateLock = [
        0,
        45,
        90,
        135,
        180,
        225,
        270,
        315
    ];

..and then user could only rotate the image 0, 45, 90, 135, 180, 225, 270 or 315 degrees?

**Comment by sotospez** [comment]
hi please check ver 0.0.7
 $scope.options.rotateRadiansLock= true;  // lock radians default true
