### ISSUE TITLE
Responsive canvases for edit-crop and view-crop?

### ISSUE THREAD

**Issue by JoeGrasso** [sotospez/sotos.crop-image#3]
While I can make the input image and watermark divs resposive to whatever device the user is using, I cannot with your edit and view canvas.

How can I make your canvases work in mobile, tablet as well as pc devices. Wight now your edit-crop and view crop do not fit nicely on a mobile device, nor small tablets.

**Comment by sotospez** [comment]
hi check v0.0.8 Responsive canvases
$scope.options.viewSizeWidth= '65%';
http://sotos.gr/demos/crop-image/mobile.html
thanks
