### ISSUE TITLE
Hard coded image saving

### ISSUE THREAD

**Issue by macluck** [sotospez/sotos.crop-image#5]
Hi,

In a listener <i>cropImageSave</i> event, a new browser window is opened. It would be more useful, if application's controller, which is calling for cropped image, could get the created inside of directive base64 image. However, referencing <i>$scope.imageOut</i> inside of application controller, like you have in example, doesn't work, because directive has an isolated scope. 
Maybe broadcasting an event, instead of calling window.open, which will contain cropped image, would be the best solution. Then it can be accessed in application logic easily.

**Comment by sotospez** [comment]
thanks fixed i think
```
<image-crop  image-out="imageOut" crop-options="options" ng-transclude crop-image-save="saveCrop">
        <edit-crop></edit-crop>
        <view-crop></view-crop>
    </image-crop>
```
in controller
```
$scope.saveCrop= function(image){
            console.log(image);
};
```
