### ISSUE TITLE
Responsive and set Width & Height.

### ISSUE THREAD

**Issue by juliogtz** [sotospez/sotos.crop-image#6]
I was trying to set width & height of viewSizeWidth & viewSizeHeight I need like "rectangule" form, but when I set the width & height with CSS the canvas like block and I can move the crop tool in the space of the image.

What do you suggest me?
I hope your response. Thank you.

![screen shot 2015-01-20 at 4 30 20 pm](https://cloud.githubusercontent.com/assets/929897/5829080/aa2fa7f4-a0c1-11e4-8199-fb7854bdfc78.png)

**Comment by sotospez** [comment]
canvas size keep the image size ratio
check this if helps you 
http://plnkr.co/edit/5BUeWv?p=preview

the problem i think is the crop toop  size if fixed
  //create the selection
  var  theSelection =  new SelectionCrop(100,100,100,100);

and if the image is small than 100 is problem 

if put css to canvas yes i see dont work you must set the size 
 $scope.options.viewSizeWidth= 500;      // canvas size default 480
 $scope.options.viewSizeHeight= 500;

this is how to set the canvas size 
                 //find ratio from canvas view to image
                 ratio_width = image.width/$scope.cropOptions.viewSizeWidth;

                if (image.width<image.height){
                     ratio_width = image.height/$scope.cropOptions.viewSizeHeight;
                }
               //set the size
                srcCanvas.width= image.width;
                srcCanvas.height= image.height;


thanks
