### ISSUE TITLE
Use bower

### ISSUE THREAD

**Issue by AlexCapi** [sotospez/sotos.crop-image#7]
Using bower in order to install your package, I got following errors : 
````
bower invalid-meta  sotos.crop-image is missing "main" entry in bower.json
bower invalid-meta  sotos.crop-image is missing "ignore" entry in bower.json
````
So there is no included files into my index.html then, and we can not initialize angular's app.

Thank you to fix it

**Comment by sotospez** [comment]
thanks i think is ok now
